---
# handlers file for roles/nvidia_gpu_exporter
- name: reload_daemon_and_restart_nvidia_gpu_exporter
  systemd:
    name: nvidia_gpu_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes