---
# tasks file for roles/nvidia_gpu_exporter
- name: check if nvidia gpu exporter exist
  stat:
    path: "{{ nvidia_gpu_exporter_bin }}"
  register: __check_nvidia_gpu_exporter_present

- name: create node exporter user
  user:
    name: "{{ nvidia_gpu_exporter_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create node exporter config dir
  file:
    path: "{{ nvidia_gpu_exporter_dir_conf }}"
    state: directory
    owner: "{{ nvidia_gpu_exporter_user }}"
    group: "{{ nvidia_gpu_exporter_group }}"

- name: download nvidia gpu exporter
  get_url:
    url: "{{ nvidia_gpu_exporter_url }}/v{{ nvidia_gpu_exporter_version }}/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_x86_64.tar.gz"
    dest: "/tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_x86_64.tar.gz"
    mode: 0755
  when: __check_nvidia_gpu_exporter_present.stat.exists == false or not __get_nvidia_gpu_exporter_version.stdout == nvidia_gpu_exporter_version
  
- name: unzip node exporter if not exist
  unarchive:
    src: "/tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_x86_64.tar.gz"
    dest: /tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_x86_64/
    remote_src: yes
  when: __check_nvidia_gpu_exporter_present.stat.exists == false or not __get_nvidia_gpu_exporter_version.stdout == nvidia_gpu_exporter_version
    
- name: move the binary to the final destination
  copy:
    src: "/tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_x86_64/nvidia_gpu_exporter"
    dest: "{{ nvidia_gpu_exporter_bin }}"
    owner: "{{ nvidia_gpu_exporter_user }}"
    group: "{{ nvidia_gpu_exporter_group }}"
    mode: 0755
    remote_src: yes
  when: __check_nvidia_gpu_exporter_present.stat.exists == false or not __get_nvidia_gpu_exporter_version.stdout == nvidia_gpu_exporter_version

- name: clean
  file:
    path: /tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_x86_64/
    state: absent
  when: __check_nvidia_gpu_exporter_present.stat.exists == false or not __get_nvidia_gpu_exporter_version.stdout == nvidia_gpu_exporter_version

- name: install service
  template:
    src: nvidia_gpu_exporter.service.in
    dest: /etc/systemd/system/nvidia_gpu_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_nvidia_gpu_exporter 

- meta: flush_handlers

- name: service always started
  systemd:
    name: nvidia_gpu_exporter
    state: started
    enabled: yes