- name: install monitoring stack
  hosts: main_node
  become: true
  roles:
  - roles/prometheus
  - roles/grafana
  
- name: install node-exporter
  hosts: all
  become: true
  roles:
  - roles/node-exporter

- name: install nvidia-gpu-exporter
  hosts: gpu_nodes
  become: true
  roles:
  - roles/nvidia_gpu_exporter